trigger:
- main
- features/*
- releases/*

jobs:
#################################################
- job: 'windows'
#################################################
  displayName: Build on Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: ci/azure-pipelines-steps.yml
    parameters:
      os: Windows_NT

#################################################
- job: 'linux'
#################################################
  displayName: Build on Linux
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - template: ci/azure-pipelines-steps.yml
    parameters:
      os: Linux

#################################################
- job: 'macOS'
#################################################
  displayName: Build on MacOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: ci/azure-pipelines-steps.yml
    parameters:
      os: MacOS
