trigger:
- main
- releases/*

jobs:
#################################################
- job: 'windows'
#################################################
  displayName: Build on Windows
  pool:
    vmImage: windows-2019
  steps:
  - template: ci/azure-pipelines-steps.yml

#################################################
- job: 'linux'
#################################################
  displayName: Build on Linux
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: ci/azure-pipelines-steps.yml

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '_build'
      artifactType: 'pipeline'
      artifactName: 'npm-package'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  - task: Npm@1
    inputs:
      command: publish
      workingDir: '_build'
      publishRegistry: useExternalRegistry
      publishEndpoint: azure-pipelines-tasks-npm
    condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'Manual'), in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/releases/*'))

#################################################
- job: 'macOS'
#################################################
  displayName: Build on MacOS
  pool:
    vmImage: macOS-11
  steps:
  - template: ci/azure-pipelines-steps.yml
