trigger:
- main
- features/*
- releases/*

jobs:
#################################################
- job: 'windows'
#################################################
  displayName: Build on Windows
  pool:
    vmImage: windows-2019
  steps:
  - template: ci/azure-pipelines-steps.yml
    parameters:
      os: Windows_NT

#################################################
- job: 'linux'
#################################################
  displayName: Build on Linux
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: ci/azure-pipelines-steps.yml
    parameters:
      os: Linux

#################################################
- job: 'macOS'
#################################################
  displayName: Build on MacOS
  pool:
    vmImage: macOS-10.15
  steps:
  - template: ci/azure-pipelines-steps.yml
    parameters:
      os: MacOS
